# This file imports the Rust extension module
# It will be automatically generated by maturin during build

try:
    from ._lib import *
except ImportError:
    # Fallback for development or when Rust extension is not available
    raise ImportError(
        "Rust extension module not found. "
        "Please ensure the package is properly installed with 'pip install -e .'"
    ) 